---
version: "3"
services:
 devopsdb:
   image: dbimage
   ports:
     - "3306:3306"
   replicas: 2

 application:
   image: appimage
   ports:
     - "1234:8080"
   replicas: 2
   depends_on:
     - "devopsdb"
